Repository Kim-Yeon-ho/BukBob_jbnu, pull requests merged in 2023-03, with the labels that each got.

#1 Update README.md
  README.md
Labels: :memo: document

#4 ✨Feature#2 기능 업데이트
  .DS_Store
  .github/.DS_Store
  .github/ISSUE_TEMPLATE/feature-issue-template.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  JBNU_FoodParser/.DS_Store
  JBNU_FoodParser/Logs/logs.txt
  JBNU_FoodParser/Module/.DS_Store
  JBNU_FoodParser/Module/FoodModule/GetFoodListModule.js
  JBNU_FoodParser/Module/FoodModule/UpdateFoodListModule.js
  JBNU_FoodParser/Module/LoggerModule/Logger.js
  JBNU_FoodParser/index.js
  JBNU_FoodParser/package-lock.json
  JBNU_FoodParser/package.json
  README.md
Labels: :sparkles: feature, :iphone: ios, :iphone: android

#6 💄 Feat/iOS 기본 UI작업을 완료헀습니다.
  JBNU_BukBob/.DS_Store
  JBNU_BukBob/BukBobWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  JBNU_BukBob/BukBobWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  JBNU_BukBob/BukBobWidget/Assets.xcassets/Contents.json
  JBNU_BukBob/BukBobWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  JBNU_BukBob/BukBobWidget/BukBobWidget.intentdefinition
  JBNU_BukBob/BukBobWidget/BukBobWidget.swift
  JBNU_BukBob/BukBobWidget/BukBobWidgetBundle.swift
  JBNU_BukBob/BukBobWidget/BukBobWidgetLiveActivity.swift
  JBNU_BukBob/BukBobWidget/Info.plist
  JBNU_BukBob/JBNU_BukBob.xcodeproj/project.pbxproj
  JBNU_BukBob/JBNU_BukBob.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  JBNU_BukBob/JBNU_BukBob.xcodeproj/project.xcworkspace/xcuserdata/kim-yeonho.xcuserdatad/UserInterfaceState.xcuserstate
  JBNU_BukBob/JBNU_BukBob.xcodeproj/xcuserdata/kim-yeonho.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  JBNU_BukBob/JBNU_BukBob.xcodeproj/xcuserdata/kim-yeonho.xcuserdatad/xcschemes/xcschememanagement.plist
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/AccentColor.colorset/Contents.json
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/AppIcon.appiconset/Contents.json
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/Contents.json
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/Images/Contents.json
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/Images/starFill.imageset/Contents.json
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/Images/starFill.imageset/starFill.png
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/Images/starNonFill.imageset/Contents.json
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/Images/starNonFill.imageset/starNonFill.png
  JBNU_BukBob/JBNU_BukBob/Assets.xcassets/MainPurple.colorset/Contents.json
  JBNU_BukBob/JBNU_BukBob/ContentView.swift
  JBNU_BukBob/JBNU_BukBob/JBNU_BukBob.xcdatamodeld/.xccurrentversion
  JBNU_BukBob/JBNU_BukBob/JBNU_BukBob.xcdatamodeld/JBNU_BukBob.xcdatamodel/contents
  JBNU_BukBob/JBNU_BukBob/JBNU_BukBobApp.swift
  JBNU_BukBob/JBNU_BukBob/MainView.swift
  JBNU_BukBob/JBNU_BukBob/Model.swift
  JBNU_BukBob/JBNU_BukBob/Persistence.swift
  JBNU_BukBob/JBNU_BukBob/Preview Content/Preview Assets.xcassets/Contents.json
  JBNU_BukBob/JBNU_BukBob/Utilites/Color+Extension.swift
  JBNU_BukBob/JBNU_BukBob/Utilites/Static.swift
  JBNU_BukBob/JBNU_BukBob/Views/MainView.swift
  JBNU_BukBob/JBNU_BukBob/Views/MenuCardView.swift
Labels: :sparkles: feature, :iphone: ios
